services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    networks:
      - bridge
    volumes:
      - /omniverse/pods/persistence/openwebui:/app/backend/data:z
    ports:
      - 8080:8080
    environment:
      - ENABLE_RAG_WEB_SEARCH=True
      - RAG_WEB_SEARCH_ENGINE=searxng
      - RAG_WEB_SEARCH_RESULT_COUNT=10
      - RAG_WEB_SEARCH_CONCURRENT_REQUESTS=30
      - SEARXNG_QUERY_URL=http://10.1.0.5:4000/search?q=<query>
      - OLLAMA_BASE_URL=http://10.1.0.5:11434
      - WEBUI_URL=http://10.1.0.5:8080

networks:
  bridge:
    driver: bridge
    
volumes:
  openwebui: {}
