services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    # volumes:
    #   - /omniverse/pods/persistence/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    #   - /omniverse/pods/persistence/nginx/cert:/etc/nginx/cert

networks:
  bridge:
    driver: bridge
    
# volumes:
#   ollama: {}