services:
  gemma-vision:
    image: docker.io/ollama/ollama:latest
    container_name: gemma-vision
    restart: unless-stopped
    devices:
      - nvidia.com/gpu=all
    networks:
      - nginx_bridge
    volumes:
      - $PERSISTENCE/gemma-vision:/root/.ollama:z
    expose:
      - 11434
    environment:
      - OLLAMA_KEEP_ALIVE=-1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  nginx_bridge:
    external: true
    
volumes:
  gemma-vision: {}
