version: "3.7"

services:
  valkey:
    image: docker.io/valkey/valkey:8-alpine
    container_name: valkey
    restart: unless-stopped
    command: valkey-server --save 30 1 --loglevel warning
    networks:
      - nginx_bridge
    volumes:
      - $PERSISTENCE/valkey:/data:z
    expose:
      - 6379
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  nginx_bridge:
    external: true

volumes:
  valkey: {}
